name: Setup
description: Sets up Node and Build SDK

inputs:
  node-version:
    required: false
    default: '18'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-${{ inputs.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-${{ inputs.node-version }}-modules-

    - name: Install Dependencies & Build
      run: yarn install --immutable --ignore-engines
      shell: bash
