name: QA

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Test
        env:
          STREAM_APP_ID: ${{ secrets.STREAM_APP_ID }}
          STREAM_API_KEY: ${{ secrets.STREAM_API_KEY }}
          STREAM_API_SECRET: ${{ secrets.STREAM_API_SECRET }}
        run: yarn run test-cloud
